### ISSUE TITLE
Autosplit not working, Timer just ends

### ISSUE THREAD

**Issue by Rovetown** [gizmovor/ASAMU_Load_Remover#1]
So whenever I finish a chapter, the Script stops the timer. There are also no Segments defined or anything, it just runs a timer and as soon as the End of the Chapter is reached, the timer stops and then never continues again.

Steps to recreate:

1. Download latest LiveSplit Version: 1.8.25
2. Load the File from GitHub or via the Search Bar
3. Set Start Time (or dont, depending on where you start)
4. go to the end of the chapter

What to expect:

- No segments in the LiveSplit Window
- Timer stopping when you end a chapter and move on to the next

**Comment by gizmovor** [comment]
you need to make one segments per chapter yourself and it will work fine.
It only auto-start, auto-split and remove load times.
It doesn't create segment for you.
I will add a line in the readme to tell people to make segments.
